### ISSUE TITLE
Koin 

### ISSUE THREAD

**Issue by Dollym89** [Freeport-Metrics/android-kotlin-starter#2]
Hi there, 
I see that you startKoin from mainActivity. I expect it would be better to start it from Application and not Activity. Now you have to recreate all dependencies every time you destroy your activity.

**Comment by krzdabrowski** [comment]
Hey, thank you for your effort and sorry for late reply - vacation time :)

You are absolutely right that would be a preferred way of starting Koin (as docs suggest as well). Timber also should be initialized this way.

However, please keep in mind that I tried to make this project as simple as possible - there's only one `Activity`, hence I haven't created separate `Application` class. One of my main goals during this project was being as consistent and "no-boilerplate'y" as possible. Moving `startKoin()` to `Application` class would mean that your injected `Context` changes from `this@MainActivity` to `this@Application`. That would create some problems, e.g. in `DialogHelper` class as you should use `Activity` context instead of `Application` one while building a dialog.

So, instead of using Koin, you would have to initialize your `DialogHelper` in a normal way like this:
`private val dialogHelper: DialogHelper by lazy { DialogHelper(this@MainActivity) }`

Not a big deal, but could be less intuitive for people reading the code and trying to understand the whole flow.

I hope you understand my point of view.
